[package]
name = "color-names-i18n"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.18", features = ["derive"] }
colors-transform = "0.2.11"
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
